spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/charliezip?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password : 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true   System.out에 하이버네이트 실행 SQL을 남기는 옵션, 로그는 왠만하면 로거로 남기는게 좋다.
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace